"""
Feature-wise Linear Modulation (FiLM) layer.

Modulates feature vectors based on a condition vector:
    h' = h * (1 + γ(z)) + β(z)

where γ, β are generated by a small MLP from the condition z,
and γ is bounded via tanh to prevent numerical explosion.

Usage:
    film = FiLMLayer(cond_dim=12, feat_dim=128)
    h_modulated = film(h, z_t)  # h: [N, 128], z_t: [12]
"""

import torch
import torch.nn as nn


class FiLMLayer(nn.Module):
    """
    A single FiLM modulation layer.

    Args:
        cond_dim:     dimension of condition vector z
        feat_dim:     dimension of feature vectors to modulate
        hidden:       hidden dim of the γ/β generator MLP
        gamma_scale:  bounds |γ| via gamma_scale * tanh(·)  (default 0.5 → γ ∈ [-0.5, 0.5])
    """

    def __init__(
        self,
        cond_dim: int,
        feat_dim: int,
        hidden: int = 128,
        gamma_scale: float = 0.5,
    ):
        super().__init__()
        self.gamma_scale = gamma_scale

        # MLP: z → [γ_raw, β]  (2 * feat_dim output)
        self.mlp = nn.Sequential(
            nn.Linear(cond_dim, hidden),
            nn.ReLU(),
            nn.Linear(hidden, 2 * feat_dim),
        )

        # Zero-init last layer → identity at start (γ=0 via tanh(0)=0, β=0)
        nn.init.zeros_(self.mlp[-1].weight)
        nn.init.zeros_(self.mlp[-1].bias)

    def forward(self, feat: torch.Tensor, cond: torch.Tensor) -> torch.Tensor:
        """
        Args:
            feat: [*, feat_dim]  — features to modulate (N nodes or E edges)
            cond: [cond_dim] or [*, cond_dim] — condition vector (auto-broadcast)
        Returns:
            modulated: [*, feat_dim]
        """
        # AMP safety: align cond dtype with feat
        cond = cond.to(dtype=feat.dtype, device=feat.device)

        params = self.mlp(cond)                          # [..., 2 * feat_dim]
        gamma_raw, beta = params.chunk(2, dim=-1)        # [..., feat_dim] each
        gamma = self.gamma_scale * torch.tanh(gamma_raw) # bounded ∈ [-scale, +scale]

        # Auto-broadcast: if cond is [feat_dim] but feat is [N, feat_dim], unsqueeze
        while gamma.dim() < feat.dim():
            gamma = gamma.unsqueeze(0)
            beta = beta.unsqueeze(0)

        return feat * (1.0 + gamma) + beta

