"""
Feature-wise Linear Modulation (FiLM) layer.

Modulates feature vectors based on a condition vector:
    h' = h * (1 + α·γ(z)) + α·β(z)

where γ, β are generated by a small MLP from the condition z,
γ is bounded via tanh to prevent numerical explosion,
and α is an external strength coefficient (supports warmup).

The layer caches γ² + β² from the last forward pass for regularization.

Usage:
    film = FiLMLayer(cond_dim=12, feat_dim=128)
    h_modulated = film(h, z_t, strength=0.5)
    reg = film.cached_reg()  # mean(γ² + β²)
"""

from typing import Optional

import torch
import torch.nn as nn


class FiLMLayer(nn.Module):
    """
    A single FiLM modulation layer with strength control and regularization.

    Args:
        cond_dim:     dimension of condition vector z
        feat_dim:     dimension of feature vectors to modulate
        hidden:       hidden dim of the γ/β generator MLP
        gamma_scale:  bounds |γ| via gamma_scale * tanh(·)  (default 0.5 → γ ∈ [-0.5, 0.5])
    """

    def __init__(
        self,
        cond_dim: int,
        feat_dim: int,
        hidden: int = 128,
        gamma_scale: float = 0.5,
    ):
        super().__init__()
        self.gamma_scale = gamma_scale

        # MLP: z → [γ_raw, β]  (2 * feat_dim output)
        self.mlp = nn.Sequential(
            nn.Linear(cond_dim, hidden),
            nn.ReLU(),
            nn.Linear(hidden, 2 * feat_dim),
        )

        # Zero-init last layer → identity at start (γ=0 via tanh(0)=0, β=0)
        nn.init.zeros_(self.mlp[-1].weight)
        nn.init.zeros_(self.mlp[-1].bias)

        self._cached_reg: Optional[torch.Tensor] = None

    def forward(
        self,
        feat: torch.Tensor,
        cond: torch.Tensor,
        strength: float = 1.0,
    ) -> torch.Tensor:
        """
        Args:
            feat:     [*, feat_dim]  — features to modulate (N nodes or E edges)
            cond:     [cond_dim] or [*, cond_dim] — condition vector (auto-broadcast)
            strength: scalar in [0, 1] — multiplied on γ and β (for warmup)
        Returns:
            modulated: [*, feat_dim]
        """
        # AMP safety: align cond dtype with feat
        cond = cond.to(dtype=feat.dtype, device=feat.device)

        params = self.mlp(cond)                          # [..., 2 * feat_dim]
        gamma_raw, beta = params.chunk(2, dim=-1)        # [..., feat_dim] each
        gamma = self.gamma_scale * torch.tanh(gamma_raw) # bounded ∈ [-scale, +scale]

        # Cache γ² + β² as live tensor (keeps gradient path for L_film regularization)
        self._cached_reg = (gamma ** 2 + beta ** 2).mean()

        # Apply strength scaling
        gamma = strength * gamma
        beta = strength * beta

        # Auto-broadcast: if cond is [feat_dim] but feat is [N, feat_dim], unsqueeze
        while gamma.dim() < feat.dim():
            gamma = gamma.unsqueeze(0)
            beta = beta.unsqueeze(0)

        return feat * (1.0 + gamma) + beta

    def cached_reg(self) -> torch.Tensor:
        """Return mean(γ² + β²) from the last forward pass (live tensor with gradients)."""
        if self._cached_reg is None:
            return torch.tensor(0.0)
        return self._cached_reg
