"""
Feature-wise Linear Modulation (FiLM) layer.

v2 (scale-only): residual scale modulation, no beta (shift):
    h' = h * (1 + strength·γ(z))

where γ is generated by MLP from condition z, bounded via tanh ∈ [-gamma_scale, +gamma_scale].
Zero-init → identity at start. Beta removed to avoid corner-specific translational bias.

The layer caches γ² from the last forward pass for L_film regularization.

Usage:
    film = FiLMLayer(cond_dim=12, feat_dim=128)
    h_modulated = film(h, z_t, strength=0.5)
    reg = film.cached_reg()  # mean(γ²)
"""

from typing import Optional

import torch
import torch.nn as nn


class FiLMLayer(nn.Module):
    """
    Scale-only FiLM modulation (no beta). Residual form: h' = h * (1 + strength·γ(z)).

    Args:
        cond_dim:     dimension of condition vector z
        feat_dim:     dimension of feature vectors to modulate
        hidden:       hidden dim of the γ generator MLP
        gamma_scale:  bounds |γ| via gamma_scale * tanh(·)  (default 0.5 → γ ∈ [-0.5, 0.5])
    """

    def __init__(
        self,
        cond_dim: int,
        feat_dim: int,
        hidden: int = 128,
        gamma_scale: float = 0.5,
    ):
        super().__init__()
        self.gamma_scale = gamma_scale

        # MLP: z → γ_raw  (feat_dim output, scale-only)
        self.mlp = nn.Sequential(
            nn.Linear(cond_dim, hidden),
            nn.ReLU(),
            nn.Linear(hidden, feat_dim),
        )

        # Zero-init last layer → identity at start (γ=0 via tanh(0)=0)
        nn.init.zeros_(self.mlp[-1].weight)
        nn.init.zeros_(self.mlp[-1].bias)

        self._cached_reg: Optional[torch.Tensor] = None

    def forward(
        self,
        feat: torch.Tensor,
        cond: torch.Tensor,
        strength: float = 1.0,
    ) -> torch.Tensor:
        """
        Args:
            feat:     [*, feat_dim]  — features to modulate (N nodes or E edges)
            cond:     [cond_dim] or [*, cond_dim] — condition vector (auto-broadcast)
            strength: scalar in [0, 1] — multiplied on γ (for warmup)
        Returns:
            modulated: [*, feat_dim]
        """
        # AMP safety: align cond dtype with feat
        cond = cond.to(dtype=feat.dtype, device=feat.device)

        gamma_raw = self.mlp(cond)                       # [..., feat_dim]
        gamma = self.gamma_scale * torch.tanh(gamma_raw)  # bounded ∈ [-scale, +scale]

        # Cache γ² as live tensor (keeps gradient path for L_film regularization)
        self._cached_reg = (gamma ** 2).mean()

        # Apply strength scaling
        gamma = strength * gamma

        # Auto-broadcast: if cond is [feat_dim] but feat is [N, feat_dim], unsqueeze
        while gamma.dim() < feat.dim():
            gamma = gamma.unsqueeze(0)

        return feat * (1.0 + gamma)

    def cached_reg(self) -> torch.Tensor:
        """Return mean(γ²) from the last forward pass (live tensor with gradients)."""
        if self._cached_reg is None:
            return torch.tensor(0.0)
        return self._cached_reg
